spring:
  datasource:
    url: jdbc:h2:~/school
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /school

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true

#actuator configuration with http calls
management:
  security:
    enabled: true

server:
  port: 8091